' Gambas module file

'    This file is part of vinstall-ng

'    vinstall-ng is free software: you can redistribute it and/or modify
'    it under the terms of the GNU General Public License as published by
'    the Free Software Foundation, either version 2 of the License, or
'    (at your option) any later version.

'    vinstall-ng  is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU General Public License for more details.

'    You should have received a copy of the GNU General Public License
'    along with vinstall-ng.  If not, see <http://www.gnu.org/licenses/>.
'====================================================================================================

PUBLIC SUB TRIGGER_HELP(fCurrStep AS Object)
  
  Message.Info("Help system not yet complete. Try again later" & "<br>" &
  fCurrStep.name)
  DEBUG "Fixme: Help system needs to be implemented" & Space(1) & "Called from " & fCurrStep.name
  
  
  
END
