' Gambas module file

'    This file is part of vinstall-ng

'    vinstall-ng is free software: you can redistribute it and/or modify
'    it under the terms of the GNU General Public License as published by
'    the Free Software Foundation, either version 2 of the License, or
'    (at your option) any later version.

'    vinstall-ng  is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU General Public License for more details.

'    You should have received a copy of the GNU General Public License
'    along with vinstall-ng.  If not, see <http://www.gnu.org/licenses/>.

PUBLIC FUNCTION ID_LANG(LangName AS String) AS String
  
  DIM sRes AS String
    SELECT CASE LangName 
      CASE "English"
        sRes = "en_US"
      CASE "Spanish"
        sRes = "es_ES"
      CASE "Russian"
        sRes = "ru_RU.utf8"
    END SELECT 
    RETURN sRes
        
  
END
