' Gambas module file
'    This file is part of vinstall-ng

'    vinstall-ng is free software: you can redistribute it and/or modify
'    it under the terms of the GNU General Public License as published by
'    the Free Software Foundation, either version 2 of the License, or
'    (at your option) any later version.

'    vinstall-ng  is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU General Public License for more details.

'    You should have received a copy of the GNU General Public License
'    along with vinstall-ng.  If not, see <http://www.gnu.org/licenses/>.

PUBLIC FUNCTION Forward(sTrFCurrent AS String) AS Form
  
  DIM fRet AS Form
  DIM sISONAME, sDev, sLang AS String
  
    SELECT CASE sTrFCurrent
   
      CASE "FrmSelISO"
        fRet = FrmPartScheme
      CASE "FrmPartScheme"
          IF ClsInstall.bUseGparted = TRUE THEN 
            Fret = FrmDiskPart
          ELSE 
            fRet = FrmPartSel
          END IF
    CASE "FrmPartsel"
          IF NOT ClsPartSel.sRoot OR ClsPartSel.sRoot = "" THEN 
            Message.Error(("You must select a \"/\" partition. This is the target where the system will install to"))
          RETURN 
          END IF
          MdlPartSel.SET_LINUX_PARTITION_TYPES()
          IF ClsPartSel.bDoWin = TRUE THEN 
            fRet = FrmWinDrives
          ELSE 
            fRet = FrmPkgSel
          END IF
    CASE "FrmDiskPart"
        'IF MdlSetup.CHECK_IF_REBOOT_NEEDED() = TRUE THEN 
          ' now need to reboot
        fRet = FrmPartSel
    'case
      
'    END IF
          
        
    END SELECT 
    
    RETURN fRet
  
  
  
END
