' Gambas module file

  
'    This file is part of vinstall-ng

'    vinstall-ng is free software: you can redistribute it and/or modify
'    it under the terms of the GNU General Public License as published by
'    the Free Software Foundation, either version 2 of the License, or
'    (at your option) any later version.

'    vinstall-ng  is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU General Public License for more details.

'    You should have received a copy of the GNU General Public License
'    along with vinstall-ng.  If not, see <http://www.gnu.org/licenses/>.

PUBLIC SUB GET_LIST_OF_SELECTED_PACKAGES()
  DIM i AS Integer
  DIM sList AS String
  
    'FrmUsrPkgSel.GridView1[0, 0].
      REPEAT 
        IF FrmUsrPkgSel.GridView1[i, 0].Picture = FrmUsrPkgSel.pYes THEN 
          sList = sList & FrmUsrPkgSel.GridView1[i, 1].Text
        END IF
        INC i
        UNTIL i = FrmUsrPkgSel.GridView1.Rows.Count
        
        Message(sList)
        
        
END
