' Gambas module file

'    This file is part of vinstall-ng

'    vinstall-ng is free software: you can redistribute it and/or modify
'    it under the terms of the GNU General Public License as published by
'    the Free Software Foundation, either version 2 of the License, or
'    (at your option) any later version.

'    vinstall-ng  is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU General Public License for more details.

'    You should have received a copy of the GNU General Public License
'    along with vinstall-ng.  If not, see <http://www.gnu.org/licenses/>.



' PUBLIC Vmlinuz AS Object[]

PRIVATE sDotConf AS String

PUBLIC FUNCTION WRITE_LILO_DOT_CONF() AS Integer
  
  DIM sGlbl AS String
  DIM iTimeout AS Integer
  DIM sTrgt AS String
  DIM sFB AS String
  
  
END





PUBLIC SUB DISPLAY_LILO_TARGET_OPTIONS()
  
  DIM sList AS String
  DIM sListarr AS String[]
  DIM i AS Integer
  DIM sTarget AS String
  DIM sDump AS String
  
    SHELL "probedisk | grep -v cdrom |cut -f 1 -d \\|" TO sList
      sList = Trim(sList)
      sListarr = Split(sList, "\n")
        FOR i = 0 TO sListarr.count - 1
          sTarget = "MBR of " & Trim(sListarr[i])
          FrmLilo.LiloTarget.Add(sTarget)
        NEXT 
        
      WITH FrmLilo.LiloTarget
          IF LCase(ClsPartSel.fRoot) <> "xfs" THEN 
          .Add("Sector")
          END IF
      SHELL "lsdev | grep floppy" TO sDump
      IF sDump <> "" THEN   
      .Add("Floppy")
      END IF
      END WITH 
  
  
END

PUBLIC SUB GENERATE_LILO_DOT_CONF()

DIM sFile AS String
DIM tb AS TextBox
DIM sShortAddr AS String
DIM sMatchTag AS String
DIM bInc AS CheckBox
DIM cb AS CheckBox
DIM sEntryLbl, sEntryApnd, sEntryRoot, sEntryInitrd, sSection AS String
DIM i AS Integer
DIM sCliSection AS String
DIM sWinSection AS String
DIM sBootAddr AS String





FOR EACH bInc IN MdlLiloOsList.bIncluded
sShortAddr = Right(bInc.tag, Len(bInc.tag) - RInStr(bInc.tag, "/"))
  IF bInc.tag = ClsPartSel.sRoot THEN 
          sBootAddr = "/boot"
        ELSE 
          sBootAddr = "/boot/tamu"
        END IF

  IF bInc.value = TRUE THEN 
    FOR EACH tb IN MdlLiloOsList.txtNames
      IF tb.Tag = bInc.tag THEN 
       sEntryLbl = tb.Text
      END IF
    NEXT 
    FOR EACH tb IN MdlLiloOsList.txtAppends
      IF tb.Tag = bInc.tag THEN 
        sEntryApnd = tb.Text
      END IF
    NEXT 
    sEntryRoot = bInc.Tag
    FOR EACH tb IN MdlLiloOsList.txtInitrds
      IF tb.tag = bInc.tag THEN 
        sEntryInitrd = tb.Text
      END IF
    NEXT 
        ' now put it in a section
      
        sSection = "image = " & sBootAddr &/ "vmlinuz-" & sShortAddr & gb.NewLine &
                    "root = " & bInc.tag & gb.NewLine &
                    "label = " & sEntryLbl & gb.NewLine &
                    "append = \"" & sEntryApnd & "\"" & gb.NewLine &
                    "initrd = " & sEntryInitrd & gb.NewLine &
                    "read-only" & " \n \n"
        
                    
        IF bInc.tag = ClsPartSel.sRoot AND MdlLiloOsList.bVlCliOption = TRUE THEN 
          sCliSection = Replace(sSection, "append = \"" & sEntryApnd & "\"", "append = \"2 " & sEntryApnd & "\"") 'splash=silent\"")
          sCliSection = Replace(sCliSection, "label = " & sEntryLbl, "label = " & sEntryLbl & "-tui")
          sCliSection = sCliSection & gb.NewLine
        ELSE 
          sCliSection = ""
        END IF
                             
    ELSE 
      sSection = ""
    
  END IF
 sFile = sFile & sCliSection & sSection
NEXT 

FOR EACH binc IN MdlLiloOsList.arrWinInstalls
  IF binc.Value = TRUE THEN 
    FOR EACH tb IN MdlLiloOsList.arrWinLabels
      IF tb.tag = binc.tag THEN 
        sEntryLbl = tb.Tag
      END IF
    NEXT 
      sWinSection = "other = " & tb.Tag & gb.NewLine &
        "label = " & tb.Text & gb.NewLine &
        "table = " & tb.Tag & "\n" & gb.NewLine
  ELSE 
    sWinSection = ""
  END IF
sFile = sFile & sWinSection
NEXT 

sDotConf = Trim(sFile)  

  
  
END

