' Gambas module file

'    This file is part of vinstall-ng

'    vinstall-ng is free software: you can redistribute it and/or modify
'    it under the terms of the GNU General Public License as published by
'    the Free Software Foundation, either version 2 of the License, or
'    (at your option) any later version.

'    vinstall-ng  is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU General Public License for more details.

'    You should have received a copy of the GNU General Public License
'    along with vinstall-ng.  If not, see <http://www.gnu.org/licenses/>.



' PUBLIC Vmlinuz AS Object[]

PUBLIC SUB DISPLAY_LILO_TARGET_OPTIONS()
  
  DIM sList AS String
  DIM sListarr AS String[]
  DIM i AS Integer
  DIM sTarget AS String
  DIM sDump AS String
  
    SHELL "probedisk | grep -v cdrom |cut -f 1 -d \\|" TO sList
      sList = Trim(sList)
      sListarr = Split(sList, "\n")
        FOR i = 0 TO sListarr.count - 1
          sTarget = "MBR of " & Trim(sListarr[i])
          FrmLilo.LiloTarget.Add(sTarget)
        NEXT 
        
      WITH FrmLilo.LiloTarget
          IF LCase(ClsPartSel.fRoot) <> "xfs" THEN 
          .Add("Sector")
          END IF
      SHELL "lsdev | grep floppy" TO sDump
      IF sDump <> "" THEN   
      .Add("Floppy")
      END IF
      END WITH 
  
  
END

PUBLIC SUB WRITE_LILO_DOT_CONF()

DIM sFile AS String
DIM sEntryLbl, sEntryApnd, sEntryRoot, sEntryInitrd AS String


  
  
  
END

