' Gambas module file

'    This file is part of vinstall-ng

'    vinstall-ng is free software: you can redistribute it and/or modify
'    it under the terms of the GNU General Public License as published by
'    the Free Software Foundation, either version 2 of the License, or
'    (at your option) any later version.

'    vinstall-ng  is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU General Public License for more details.

'    You should have received a copy of the GNU General Public License
'    along with vinstall-ng.  If not, see <http://www.gnu.org/licenses/>.

PUBLIC SUB LIST_EXISTING_ACCOUNTS()
  
  DIM sDir AS String
    FOR EACH sdir IN Dir(ClsGlobal.sTargetMnt &/ "home", "*", gb.Directory)
      IF sdir <> "ftp" THEN 
      IF sdir <> "lost+found" THEN 
        IF FrmImportAccts.cbAccntList.Find(sdir) = -1 THEN 
          FrmImportAccts.cbAccntList.Add(sdir)
        END IF
      END IF
    END IF
    NEXT 
  
END
