' Gambas module file

'    This file is part of vinstall-ng

'    vinstall-ng is free software: you can redistribute it and/or modify
'    it under the terms of the GNU General Public License as published by
'    the Free Software Foundation, either version 2 of the License, or
'    (at your option) any later version.

'    vinstall-ng  is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU General Public License for more details.

'    You should have received a copy of the GNU General Public License
'    along with vinstall-ng.  If not, see <http://www.gnu.org/licenses/>.

PUBLIC SUB SUMMARIZE_INSTALL()
  
DIM sText AS String
DIM i AS Integer  
  ' read each partition type
  MdlPartSel.SET_LINUX_PARTITION_TYPES()
  'Message(ClsPartSel.fRoot)
  
  
  sText = "<b><br>" & ("PARTITIONING LAYOUT") & ":</b><br>" &
  ClsPartSel.sRoot & " = / (" & ClsPartSel.fRoot & ")<br>"
  '"/ = " & ClsPartSel.sRoot & " <br>" 
    IF ClsPartSel.sHome THEN 
      sText = sText & ClsPartSel.sHome & " = /home (" & ClsPartSel.fhome & ")<br>"
    END IF
    IF ClsPartSel.sOpt THEN 
      sText = sText & ClsPartSel.sOpt & " = /opt (" & ClsPartSel.fOpt & ")<br>"
    END IF
    IF ClsPartSel.sUsr THEN 
      sText = sText & ClsPartSel.sUsr & " = /usr (" & ClsPartSel.fUsr & ")<br>"
    END IF
    IF ClsPartSel.sTmp THEN 
      sText = sText & ClsPartSel.sTmp & " = /tmp (" & ClsPartSel.fTmp & ")<br>"
    END IF
    IF ClsPartSel.sVar THEN 
      sText = sText & ClsPartSel.sVar & " = /var (" & ClsPartSel.sVar & ")<br>"
    END IF
    
    sText = sText & "<br><br>"
    
    IF ClsWinDrives.sWinDrives THEN 
    sText = sText & "<b>" & ("OPTIONAL WINDOWS PARTITIONS TO BE MOUNTED AT BOOT TIME.") & "</b><br>"
      'list all the windows partitions here
      sText = sText & ME.LIST_WINDOWS_PARTITIONS() & "<bb><br>"
    END IF
    
    IF ClsPkgSel.bCustom = TRUE THEN 
        FrmSummary.tlSummary.Height = FrmSummary.scrSumm.Height * 1.5
      sText = sText & "<b>" & ("INSTALL TYPE:") & "</b>" & Space(1) & ("Custom") & "<br>"
      
       sText = sText & "<br><b>" & ("BULK PACKAGES:") & "</b> "
    FOR i = 0 TO ClsPkgSel.arrBulks.Count - 1
      sText = sText & "<br>" & Right(ClsPkgSel.arrBulks[i], Len(ClsPkgSel.arrBulks[i]) - RInStr(ClsPkgSel.arrBulks[i], "/"))
    NEXT 
    sText = sText & "<br><br><b>" & ("OPTIONAL PACKAGES:") & "</b>"
      FOR i = 0 TO ClsPkgSel.arrPkgs.Count - 1
        sText = sText & "<br>" & Right(ClsPkgSel.arrPkgs[i], Len(ClsPkgSel.arrPkgs[i]) - RInStr(ClsPkgSel.arrPkgs[i], "/"))
      NEXT       
      
    ELSE 
      FrmSummary.tlSummary.Height = FrmSummary.scrSumm.Height * 0.75
      sText = sText & "<b>" & ("INSTALL TYPE:") & "</b>" & Space(1) & ("Full") & "<br>"
      
    END IF

               
               
   
  FrmSummary.tlSummary.Text = sText

  
  
  
END

  PUBLIC FUNCTION LIST_WINDOWS_PARTITIONS() AS String
  
    DIM sPart, sMntPnt, sLine, sRet, sNewLine AS String
    DIM i AS Integer
      IF ClsWinDrives.sWinDrives THEN 
        FOR i = 0 TO ClsWinDrives.sWinDrives.Count - 1
          sLine = ClsWinDrives.sWinDrives[i]
          spart = Trim(Left(sLine, InStr(sLine, "|") - 1))
          sMntPnt = Right(sLine, Len(sLine) - InStr(sLine, "|"))
          sRet = sRet & "<br>" & spart & " will be mounted to " & sMntPnt
          'Message.Info(sLine)
        NEXT 
        sRet = Trim(sRet)
        RETURN sRet
      END IF
          
        
        
    
  
END

